### ISSUE TITLE
Update for VS 2019

### ISSUE THREAD

**Issue by gouldingken** [mcneel/RhinoCommonTemplatePackage#9]
Rhino Templates cannot currently be loaded into VS 2019. I suspect this is owing to a flag in the manifest file rather than any limitation in VS 2019.

Please update accordingly.

**Comment by maxsu** [comment]
@gouldingken Thanks for your suggestion. A simple [version bump](https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/) seems to fix the issue. See PR #10 if you need a fix asap.

A note of caution: I've tested the default plugin template only.

**Comment by piac** [comment]
This was fixed

**Comment by piac** [comment]
This was fixed. Thanks for your help with it. @gouldingken
